@extends('layouts.blank')

@section('styles')
    <style>
        .page-break {
            page-break-after: auto;
        }
    </style>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <h1 class="page-header text-right">
                Report For {{ title_case($sort) }} Rent Collection
            </h1>

            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <td colspan="2" class="text-right">
                            {{ $company->title }}<br>
                            {{ $company->address }}<br>
                            {{ $company->state }}, {{ $company->city }} {{ $company->zipcode }}<br>
                            {{ $company->phone }}
                        </td>
                    </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>

    <hr>
    @foreach($rents->chunk(10) as $_rents)
        <div class="row">
            <div class="col-md-12">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Property</th>
                        <th>Tenant</th>
                        <th>For</th>
                        <th>Amount</th>
                        <th>Date Due.</th>
                        <th>Status</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($_rents as $rent)
                        <tr>
                            <td>
                                {{ $rent->id }}
                            </td>
                            <td>{{ $rent->property->title }}</td>
                            <td>
                                {{ $rent->lease->tenant->user->firstname }}
                                {{ $rent->lease->tenant->user->lastname }}
                            </td>
                            <td>
                                {{ MonthName($rent->date_from) }} - {{ MonthName($rent->date_to) }}
                            </td>
                            <td>{{ $rent->amount }}</td>
                            <td>{{ $rent->date_due }}</td>
                            <td>{{ RentStatusText($rent->status) }}</td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <td colspan="2" class="text-right">
                                <strong>
                                    Report generated by:
                                    <br>
                                    {{ config('app.name') }}, Inc
                                </strong>
                                <br>
                                <strong>www.smartville.co</strong>
                            </td>
                        </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>

        <div class="page-break"></div>
    @endforeach

@endsection